### PR TITLE
add a setting to allow for double-click in Find Results pane

### PR DESCRIPTION
**Pull request by pomeh**
Follow up for my comment at https://github.com/titoBouzout/FindResultsApplyChanges/issues/10#issuecomment-161459379

What are your though with this ?

### CODE REVIEW

**Comment by pomeh** [comment]
ping @titoBouzout

**Comment by titoBouzout** [comment]
Hi sorry for delay, would you mind to put the setting on own file? FindExcludePatterns.sublime-settings  instead of using the global Preferences.sublime-settings

**Comment by pomeh** [comment]
I've updated the pull request. To be coherent with the package name I've used `FindResultsApplyChanges.sublime-settings` instead of `FindExcludePatterns.sublime-settings` for the settings filename

What are your thoughts now ?

**Comment by titoBouzout** [comment]
Thank you looks great at first glance

**Comment by lrobeson** [comment]
FINALLY! I've been wondering why this feature stopped working. I'm curious what the reasoning is behind disabling it by default?

Either way, I love this plugin, thanks for your work on it!

**Comment by titoBouzout** [comment]
Because double clicking a word in a text editor should never open a file? Maybe CTRL+Click or ALT+CLick, but double click?? ><

**Pull request merged**
